FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm config set registry="http://registry.npmjs.org/"
RUN npm install

# RUN chown -R node:node /app/node_modules

COPY . .

CMD ["npm", "run", "start"]